#!/bin/bash

DOCKER_CLI_EXPERIMENTAL="enabled"
DIND="docker run --rm docker"

${DIND} sh -c "\
  export DOCKER_CLI_EXPERIMENTAL='${DOCKER_CLI_EXPERIMENTAL}' && \
  docker login -u '${MY_DOCKER_USERNAME}' -p '${MY_DOCKER_PASSWORD}' && \
  docker manifest create melsonlai/docker-megacmd:latest \
    melsonlai/docker-megacmd:amd64 \
    melsonlai/docker-megacmd:arm && \
  docker manifest push melsonlai/docker-megacmd:latest \
"
